
import type { AudioSettings } from './types';

export const DEFAULT_AUDIO_SETTINGS: AudioSettings = {
  pitch: 0.5,
  tempo: 0.8,
  bass: 0,
  mid: 0,
  treble: 0,
  reverb: {
    wet: 0,
    decay: 1.0,
    preDelay: 0,
    roomSize: 0.5,
  },
  compression: {
    threshold: -20,
    ratio: 4,
    attack: 10,
    release: 100,
  },
  delay: {
    time: 0,
    feedback: 0,
    mix: 0,
  },
  filter: {
    type: 'none',
    frequency: 1000,
    q: 1,
  },
  stereo: {
    width: 1,
    balance: 0,
  },
};

// Emotional presets for transforming audio mood
export const EMOTIONAL_PRESETS: Record<string, AudioSettings> = {
  happy: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: 2,
    mid: 1,
    treble: 3,
    reverb: { wet: 0.2, decay: 0.8, preDelay: 10, roomSize: 0.6 },
    compression: { threshold: -15, ratio: 3, attack: 5, release: 50 },
    delay: { time: 0, feedback: 0, mix: 0 },
    filter: { type: 'none', frequency: 1000, q: 1 },
    stereo: { width: 1.2, balance: 0 },
  },
  
  sad: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: -2,
    mid: -1,
    treble: -3,
    reverb: { wet: 0.4, decay: 2.5, preDelay: 50, roomSize: 0.8 },
    compression: { threshold: -25, ratio: 6, attack: 20, release: 200 },
    delay: { time: 800, feedback: 0.3, mix: 0.2 },
    filter: { type: 'lowpass', frequency: 3000, q: 0.8 },
    stereo: { width: 0.8, balance: 0 },
  },
  
  energetic: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: 4,
    mid: 2,
    treble: 5,
    reverb: { wet: 0.1, decay: 0.5, preDelay: 5, roomSize: 0.4 },
    compression: { threshold: -10, ratio: 2, attack: 2, release: 30 },
    delay: { time: 200, feedback: 0.2, mix: 0.15 },
    filter: { type: 'none', frequency: 1000, q: 1 },
    stereo: { width: 1.3, balance: 0 },
  },
  
  calm: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: 1,
    mid: 0,
    treble: -1,
    reverb: { wet: 0.3, decay: 1.5, preDelay: 30, roomSize: 0.7 },
    compression: { threshold: -20, ratio: 4, attack: 15, release: 150 },
    delay: { time: 0, feedback: 0, mix: 0 },
    filter: { type: 'lowpass', frequency: 5000, q: 0.6 },
    stereo: { width: 1.1, balance: 0 },
  },
  
  mysterious: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: 3,
    mid: -2,
    treble: -4,
    reverb: { wet: 0.5, decay: 3.0, preDelay: 80, roomSize: 0.9 },
    compression: { threshold: -30, ratio: 8, attack: 25, release: 300 },
    delay: { time: 1200, feedback: 0.4, mix: 0.25 },
    filter: { type: 'lowpass', frequency: 2000, q: 1.2 },
    stereo: { width: 0.7, balance: 0 },
  },
  
  intimate: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: 2,
    mid: 1,
    treble: 0,
    reverb: { wet: 0.15, decay: 0.6, preDelay: 15, roomSize: 0.3 },
    compression: { threshold: -18, ratio: 3, attack: 8, release: 80 },
    delay: { time: 0, feedback: 0, mix: 0 },
    filter: { type: 'none', frequency: 1000, q: 1 },
    stereo: { width: 0.9, balance: 0 },
  },
  
  epic: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: 6,
    mid: 3,
    treble: 4,
    reverb: { wet: 0.4, decay: 4.0, preDelay: 100, roomSize: 0.9 },
    compression: { threshold: -12, ratio: 2.5, attack: 3, release: 40 },
    delay: { time: 600, feedback: 0.3, mix: 0.2 },
    filter: { type: 'none', frequency: 1000, q: 1 },
    stereo: { width: 1.4, balance: 0 },
  },
  
  dreamy: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: 1,
    mid: -1,
    treble: 2,
    reverb: { wet: 0.6, decay: 3.5, preDelay: 120, roomSize: 0.95 },
    compression: { threshold: -25, ratio: 5, attack: 20, release: 250 },
    delay: { time: 1500, feedback: 0.5, mix: 0.3 },
    filter: { type: 'lowpass', frequency: 4000, q: 0.7 },
    stereo: { width: 1.2, balance: 0 },
  },
  
  aggressive: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: 5,
    mid: 4,
    treble: 6,
    reverb: { wet: 0.1, decay: 0.3, preDelay: 2, roomSize: 0.2 },
    compression: { threshold: -8, ratio: 1.5, attack: 1, release: 20 },
    delay: { time: 100, feedback: 0.1, mix: 0.1 },
    filter: { type: 'highpass', frequency: 80, q: 0.8 },
    stereo: { width: 1.1, balance: 0 },
  },
  
  romantic: {
    ...DEFAULT_AUDIO_SETTINGS,
    pitch: 0.5,
    tempo: 0.8,
    bass: 2,
    mid: 1,
    treble: 1,
    reverb: { wet: 0.25, decay: 2.0, preDelay: 40, roomSize: 0.75 },
    compression: { threshold: -22, ratio: 4, attack: 12, release: 120 },
    delay: { time: 400, feedback: 0.25, mix: 0.18 },
    filter: { type: 'none', frequency: 1000, q: 1 },
    stereo: { width: 1.15, balance: 0 },
  },
};
